### ISSUE TITLE
Problem while building the image for food truck app

### ISSUE THREAD

**Issue by leanh1188** [prakhar1989/docker-curriculum#246] opened 2020-05-01 11:32 UTC
Hi,
while building the image for the food truck app, i'm getting the following error:

Step 1/13 : FROM ubuntu:latest
 ---> 1d622ef86b13
Step 2/13 : LABEL maintainer="Prakhar Srivastav <prakhar@prakhar.me>"
 ---> Using cache
 ---> f3e58a4565d0
Step 3/13 : RUN apt-get -yqq update
 ---> Using cache
 ---> f9ccb62736e7
Step 4/13 : RUN apt-get -yqq install python-pip python-dev curl gnupg
 ---> Running in 7bd7649298cf
E: Unable to locate package python-pip
The command '/bin/sh -c apt-get -yqq install python-pip python-dev curl gnupg' returned a non-zero code: 100

Does anybody have also this error and know how to fix it ?

**Comment by moorekwon** [comment] 2020-05-01 12:04
I am also faced with the problem. I changed versions of pip/python to pip3/python3 in Dockerfile, but the app.py is made of python, so I can't run. Other errors occur in app.py. It seems the newly updated ubuntu only accepts python3-pip, not python-pip in Docker.

**Comment by leanh1188** [comment] 2020-05-01 14:25
> I changed version of ubuntu to 18.04 in Dockerfile, and it seems work.

Thank for the tip. It works now

**Comment by shelsoloa** [comment] 2020-05-12 20:15
The problem is using python 2 instead of python 3. I made a PR for supporting Python 3 here: prakhar1989/FoodTrucks#30

**Comment by prakhar1989** [comment] 2020-05-19 03:57
This should be fixed now.. please follow the updated tutorial and let me know if this is still causing issues.

**Closed** 2020-05-29 17:40 UTC
Labels: waiting-for-response
