### ISSUE TITLE
Kubernetes-Curriculum

### ISSUE THREAD

**Issue by mainstringargs** [prakhar1989/docker-curriculum#200] opened 2019-10-01 17:00 UTC
Stumbled on this tutorial.  Awesome job!!  It really helped solidify the concepts.  Any chance you'd create a Kubernetes version?  Or do you know of a tutorial that is similar in concept?

**Comment by prakhar1989** [comment] 2020-04-20 00:03
Duplicate of #8

**Closed by prakhar1989** 2020-04-20 00:03 UTC
Labels: feature-request
